export type Image =
  | '404'
  | 'belive'
  | 'blue_lemons'
  | 'cart'
  | 'choose-the-best'
  | 'cookies'
  | 'get-fresh'
  | 'green_cucumber'
  | 'land'
  | 'salad'
  | 'thank-for-order'
  | 'tomatoes'
  | 'what-customer'
  | 'yello-drink'
