name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  typecheck:
    uses: ./.github/workflows/typecheck.yml

  build:
    needs: [lint, typecheck]
    uses: ./.github/workflows/build.yml

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build]
    uses: ./.github/workflows/deploy.yml
